import { Artist, Playlist, Song } from "@/lib/types";

export const artists: Artist[] = [
  { id: "artist-nova", name: "Nova Lane", tagline: "dreamy electro-pop pulses" },
  { id: "artist-cinder", name: "Cinder Row", tagline: "cinematic alt-rock pressure release" },
  { id: "artist-ember", name: "Ember Vale", tagline: "warm hooks with neon edges" },
  { id: "artist-rain", name: "Rain Archive", tagline: "ambient field recordings and soft synth pads" },
  { id: "artist-kairo", name: "Kairo Set", tagline: "instrumental focus sessions for late nights" },
];

export const songs: Song[] = [
  {
    id: "song-sunup",
    title: "Sunup Run",
    artistId: "artist-ember",
    mood: "happy",
    genres: ["Pop", "Dance"],
    bpm: [122, 132],
    energy: "high",
    duration: 196,
    color: "#ffb800",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    lyrics: ["Golden city in my headphones", "Every step lands on the beat", "Turn the skyline into chorus"],
  },
  {
    id: "song-citrus",
    title: "Citrus Sparks",
    artistId: "artist-ember",
    mood: "happy",
    genres: ["Pop", "Funk"],
    bpm: [104, 120],
    energy: "high",
    duration: 214,
    color: "#ff7a18",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    lyrics: ["Color floods the morning", "Every window turns to light", "You and I outrun the static"],
  },
  {
    id: "song-bluehour",
    title: "Blue Hour Letters",
    artistId: "artist-rain",
    mood: "sad",
    genres: ["Acoustic", "Indie"],
    bpm: [68, 84],
    energy: "low",
    duration: 228,
    color: "#5b8cff",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    lyrics: ["Streetlights melt into rivers", "I write your name in quieter tones", "Some nights only ask to be heard"],
  },
  {
    id: "song-glassrain",
    title: "Glass Rain",
    artistId: "artist-rain",
    mood: "sad",
    genres: ["Indie", "Ambient"],
    bpm: [60, 78],
    energy: "low",
    duration: 245,
    color: "#7ad7ff",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    lyrics: ["Blur the city into blue", "Let the silence keep the melody", "Gentle hearts survive the storm"],
  },
  {
    id: "song-redline",
    title: "Redline Ritual",
    artistId: "artist-cinder",
    mood: "angry",
    genres: ["Rock", "Rap"],
    bpm: [134, 154],
    energy: "high",
    duration: 188,
    color: "#ff4d5a",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    lyrics: ["Break the ceiling, raise the voltage", "Pressure turns to fuel tonight", "All the noise becomes momentum"],
  },
  {
    id: "song-static",
    title: "Static Teeth",
    artistId: "artist-cinder",
    mood: "angry",
    genres: ["Rap", "Industrial"],
    bpm: [128, 146],
    energy: "high",
    duration: 201,
    color: "#ff7b54",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    lyrics: ["Hands shake sparks from the rails", "Turn the friction into thunder", "Move until the pulse breaks open"],
  },
  {
    id: "song-softskies",
    title: "Soft Skies",
    artistId: "artist-rain",
    mood: "calm",
    genres: ["Lo-fi", "Ambient"],
    bpm: [56, 72],
    energy: "low",
    duration: 232,
    color: "#7b61ff",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    lyrics: ["Float the room into violet", "Every breath slows the night", "Quiet water under neon"],
  },
  {
    id: "song-evening",
    title: "Evening Exhale",
    artistId: "artist-rain",
    mood: "calm",
    genres: ["Ambient", "Chill"],
    bpm: [50, 68],
    energy: "low",
    duration: 264,
    color: "#3ddc97",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    lyrics: ["The city goes soft at the edges", "Lamplight hums in slow circles", "Night arrives without asking"],
  },
  {
    id: "song-grid",
    title: "Grid Focus",
    artistId: "artist-kairo",
    mood: "focus",
    genres: ["Instrumental", "Electronic"],
    bpm: [88, 102],
    energy: "medium",
    duration: 219,
    color: "#4da6ff",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    lyrics: ["Instrumental focus marker", "No lyrics, only motion", "Steady structure forward"],
  },
  {
    id: "song-blueprint",
    title: "Blueprint Drift",
    artistId: "artist-kairo",
    mood: "focus",
    genres: ["Instrumental", "Lo-fi"],
    bpm: [76, 94],
    energy: "medium",
    duration: 252,
    color: "#9bffb0",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    lyrics: ["Numbers settle into rhythm", "Thoughts align and sharpen", "A clean desk inside the head"],
  },
];

export const playlists: Playlist[] = [
  {
    id: "playlist-happy",
    title: "Golden Rush",
    description: "Pop and dance cuts built for brighter rooms and faster grins.",
    mood: "happy",
    songIds: ["song-sunup", "song-citrus"],
    accent: "#ffb800",
  },
  {
    id: "playlist-sad",
    title: "Midnight Blue",
    description: "Acoustic and indie textures that sit with the feeling instead of rushing it.",
    mood: "sad",
    songIds: ["song-bluehour", "song-glassrain"],
    accent: "#5b8cff",
  },
  {
    id: "playlist-angry",
    title: "Pressure Release",
    description: "Sharp drums, hard edges, and loud momentum for letting it out cleanly.",
    mood: "angry",
    songIds: ["song-redline", "song-static"],
    accent: "#ff4d5a",
  },
  {
    id: "playlist-calm",
    title: "Evening Calm",
    description: "Slow, floating sounds for exhaling into softer light.",
    mood: "calm",
    songIds: ["song-softskies", "song-evening"],
    accent: "#7b61ff",
  },
  {
    id: "playlist-focus",
    title: "Signal Lock",
    description: "Instrumental sessions tuned for clean attention and longer stretches.",
    mood: "focus",
    songIds: ["song-grid", "song-blueprint"],
    accent: "#4da6ff",
  },
];
